# Generated by Django 4.0.4 on 2022-05-19 20:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailauthentication_user_phone_number_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthentication',
            name='code',
            field=models.CharField(default=users.models.EmailAuthentication.get_random_code, editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='emailauthentication',
            name='code_time',
            field=models.FloatField(default=users.models.EmailAuthentication.get_current_time, editable=False),
        ),
    ]
