# Generated by Django 4.0.4 on 2022-06-15 21:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailauthentication_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=users.models.PasswordReset.get_random_code, editable=False, max_length=6)),
                ('code_time', models.FloatField(default=users.models.PasswordReset.get_current_time, editable=False)),
                ('validated', models.BooleanField(default=False)),
                ('validation_time', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to=users.models.User.profile_picture_filepath),
        ),
    ]
