# Generated by Django 4.0.5 on 2022-06-16 19:18

from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordreset_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
