# Generated by Django 4.0.6 on 2022-08-05 06:03

from django.db import migrations, models
import phonenumber_field.modelfields
import users.generics


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_latitude_user_longitude_alter_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('code', models.CharField(default=users.generics.get_random_code, editable=False, max_length=6)),
                ('code_time', models.FloatField(default=users.generics.get_current_time, editable=False)),
                ('validated', models.BooleanField(default=False)),
                ('validation_time', models.FloatField(null=True)),
            ],
        ),
    ]
