# Generated by Django 4.0.6 on 2022-08-09 03:59

from django.db import migrations, models
import phonenumber_field.modelfields
import users.generics


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_phonenumberauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthentication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumberauthentication',
            name='code',
            field=models.CharField(default=users.generics.get_random_code, max_length=6),
        ),
        migrations.AlterField(
            model_name='phonenumberauthentication',
            name='code_time',
            field=models.FloatField(default=users.generics.get_current_time),
        ),
        migrations.AlterField(
            model_name='phonenumberauthentication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumberauthentication',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
