# Generated by Django 4.0.6 on 2022-08-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_phonenumberreset_email_code_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberreset',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
