# Generated by Django 4.0.6 on 2022-08-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_phonenumberreset_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumberreset',
            old_name='validated',
            new_name='email_validated',
        ),
        migrations.RenameField(
            model_name='phonenumberreset',
            old_name='validation_time',
            new_name='email_validation_time',
        ),
        migrations.AddField(
            model_name='phonenumberreset',
            name='phone_number_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumberreset',
            name='phone_number_validation_time',
            field=models.FloatField(null=True),
        ),
    ]
