# Generated by Django 4.0.6 on 2022-08-11 04:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_validated_phonenumberreset_email_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberreset',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
