# Generated by Django 4.0.6 on 2022-08-11 04:58

from django.db import migrations, models
import users.generics


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_phonenumberreset_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberreset',
            name='reset_token',
            field=models.CharField(default=users.generics.get_random_code, max_length=6),
        ),
    ]
