# Generated by Django 4.0.7 on 2022-08-22 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=5),
        ),
    ]
