# Generated by Django 4.0.7 on 2022-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberauthentication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
