# Generated by Django 4.0.7 on 2022-08-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_phonenumberauthentication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberauthentication',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
