# Generated by Django 4.0.7 on 2022-08-30 17:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_is_validated_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_picture',
            field=models.ImageField(null=True, upload_to=users.models.User.confirm_profile_picture_filepath),
        ),
    ]
