# Generated by Django 4.0.7 on 2022-08-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hidden',
            new_name='is_hidden',
        ),
    ]
