# Generated by Django 4.0.7 on 2022-09-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_hidden_user_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pending_verification',
            field=models.BooleanField(default=False),
        ),
    ]
