# Generated by Django 4.0.7 on 2022-09-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_is_pending_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keywords',
        ),
    ]
