# Generated by Django 4.0.7 on 2022-09-09 04:27

from django.db import migrations, models
import users.models

def save_thumbnails_for_all_users(apps, schema_editor):
    from sorl.thumbnail import get_thumbnail

    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.User.thumbnail_filepath),
        ),
        migrations.RunPython(save_thumbnails_for_all_users, migrations.RunPython.noop),
    ]
