# Generated by Django 4.0.7 on 2022-09-19 23:57

from django.db import migrations


def remove_accounts_without_phone_numbers(apps, schema_editor):
    from sorl.thumbnail import get_thumbnail

    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if not user.phone_number:
            user.delete()
    return

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RunPython(remove_accounts_without_phone_numbers, migrations.RunPython.noop),
    ]
