# Generated by Django 4.0.7 on 2022-09-20 00:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_date_of_birth_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='email',
        ),
        migrations.AddField(
            model_name='ban',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
