# Generated by Django 4.0.7 on 2022-09-23 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_user_notification_badge_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessageactivity',
            name='sangdaebang',
        ),
        migrations.RemoveField(
            model_name='usermessageactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermistboxactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='sangdaebang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserMentionsActivity',
        ),
        migrations.DeleteModel(
            name='UserMessageActivity',
        ),
        migrations.DeleteModel(
            name='UserMistboxActivity',
        ),
    ]
