# Generated by Django 4.0.7 on 2022-09-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_notification_sangdaebang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'message'), ('tag', 'tag'), ('dailymistbox', 'dailymistbox'), ('comment', 'comment')], max_length=15),
        ),
    ]
