# Generated by Django 4.0.7 on 2022-09-24 01:48

import django.contrib.postgres.fields
from django.db import migrations, models
import users.generics


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_prompts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=users.generics.get_empty_prompts, size=3),
        ),
    ]
