# Generated by Django 4.0.7 on 2022-09-24 22:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_user_confirm_picture_alter_user_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.User.confirm_profile_picture_filepath),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.User.profile_picture_filepath),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.User.thumbnail_filepath),
        ),
    ]
