# Generated by Django 4.0.7 on 2022-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_user_confirm_picture_alter_user_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_user',
            field=models.BooleanField(default=False),
        ),
    ]
