# Generated by Django 4.0.7 on 2022-09-24 23:45

from django.db import migrations

def reset_null_thumbnails(apps, schema_editor):
    from django.core.files.base import ContentFile
    from sorl.thumbnail import get_thumbnail

    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if not user.thumbnail and user.picture:
            resized = get_thumbnail(user.picture, '100x100', quality=99)
            user.thumbnail.save(resized.name, ContentFile(resized.read()), False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20220924_2307'),
    ]

    operations = [
        migrations.RunPython(reset_null_thumbnails, migrations.RunPython.noop),
    ]
