# Generated by Django 4.0.7 on 2022-09-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_rename_notification_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('message', 'message'), ('tag', 'tag'), ('comment', 'comment')], max_length=15),
        ),
    ]
