# Generated by Django 4.0.2 on 2022-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0002_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to='mist.Profile'),
        ),
    ]
