# Generated by Django 4.0.4 on 2022-05-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='EmailAuthentication',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
