# Generated by Django 4.0.4 on 2022-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0004_alter_comment_timestamp_alter_flag_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
