# Generated by Django 4.0.3 on 2022-03-09 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0004_remove_comment_date_remove_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.profile')),
            ],
        ),
    ]
