# Generated by Django 4.0.3 on 2022-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0005_remove_post_votes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
