# Generated by Django 4.0.4 on 2022-05-20 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mist.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0005_alter_flag_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=mist.models.get_current_time, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post')),
                ('tagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_user', to=settings.AUTH_USER_MODEL)),
                ('tagging_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tagged_user', 'tagging_user')},
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=mist.models.get_current_time, null=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to=settings.AUTH_USER_MODEL)),
                ('blocking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocking_user', 'blocked_user')},
            },
        ),
    ]
