# Generated by Django 4.0.4 on 2022-05-22 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mist.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0006_tag_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=mist.models.get_current_time, null=True)),
                ('friend_requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requested_user', to=settings.AUTH_USER_MODEL)),
                ('friend_requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requesting_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('friend_requesting_user', 'friend_requested_user')},
            },
        ),
    ]
