# Generated by Django 4.0.3 on 2022-03-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0007_flag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'post')},
        ),
    ]
