# Generated by Django 4.0.4 on 2022-05-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0007_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='to_user',
            new_name='sender',
        ),
    ]
