# Generated by Django 4.0.3 on 2022-03-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0008_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('flagger', 'post')},
        ),
    ]
