# Generated by Django 4.0.4 on 2022-06-08 19:49

from django.db import migrations, models
import django.db.models.deletion
import mist.models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0010_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=mist.models.get_current_time)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post')),
            ],
        ),
    ]
