# Generated by Django 4.0.3 on 2022-03-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0011_registrationrequest_validationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('occurrences', models.IntegerField()),
            ],
        ),
    ]
