# Generated by Django 4.0.4 on 2022-06-09 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mist.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0011_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=mist.models.get_current_time, null=True)),
                ('match_requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requested_user', to=settings.AUTH_USER_MODEL)),
                ('match_requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requesting_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match_requesting_user', 'match_requested_user')},
            },
        ),
    ]
