# Generated by Django 4.0.4 on 2022-06-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0012_matchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
            preserve_default=False,
        ),
    ]
