# Generated by Django 4.0.3 on 2022-03-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0012_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('code_time', models.FloatField()),
                ('validated', models.BooleanField()),
                ('validation_time', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='validationrequest',
            name='registration',
        ),
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
        migrations.DeleteModel(
            name='ValidationRequest',
        ),
    ]
