# Generated by Django 4.0.3 on 2022-03-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0013_registration_remove_validationrequest_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
