# Generated by Django 4.0.3 on 2022-03-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0014_alter_registration_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='occurrences',
        ),
        migrations.AddField(
            model_name='word',
            name='posts',
            field=models.ManyToManyField(to='mist.post'),
        ),
    ]
