# Generated by Django 4.0.4 on 2022-06-15 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0014_alter_matchrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('post', 'favoriting_user')},
        ),
    ]
