# Generated by Django 4.0.3 on 2022-03-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0015_remove_word_occurrences_word_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=34.0224, max_digits=22),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=118.2851, max_digits=22),
        ),
    ]
