# Generated by Django 4.0.5 on 2022-06-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0016_rename_text_comment_body_rename_text_message_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='body',
            new_name='text',
        ),
    ]
