# Generated by Django 4.0.3 on 2022-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0017_remove_post_location_alter_post_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
