# Generated by Django 4.0.3 on 2022-03-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0018_alter_post_latitude_alter_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location_description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
