# Generated by Django 4.0.3 on 2022-03-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0021_remove_profile_pic_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
