# Generated by Django 4.0.5 on 2022-07-26 20:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0021_alter_matchrequest_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flag',
            new_name='PostFlag',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='PostVote',
        ),
    ]
