# Generated by Django 4.0.5 on 2022-07-26 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mist.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0022_rename_flag_postflag_rename_vote_postvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=mist.models.get_current_time)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.comment')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='CommentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=mist.models.get_current_time)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.comment')),
                ('flagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flagger', 'comment')},
            },
        ),
    ]
