# Generated by Django 4.0.6 on 2022-07-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0023_commentvote_commentflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvote',
            name='emoji',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
