# Generated by Django 4.0.4 on 2022-05-15 19:56

from django.db import migrations, models

def create_ids(apps, schema_editor):
    Profile = apps.get_model('mist', 'Profile')
    profiles = Profile.objects.all()
    i = 1
    for p in profiles:
        p.id = i
        i += 1
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0023_account_alter_comment_author_alter_flag_flagger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=create_ids,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
