# Generated by Django 4.0.6 on 2022-08-04 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0025_alter_postvote_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagged_name',
            field=models.CharField(default='anonymous', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagged_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagging_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagging_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
