# Generated by Django 4.0.4 on 2022-05-15 20:06
from django.conf import settings
from django.db import migrations, models

def match(apps, schema_editor):
    Profile = apps.get_model('mist', 'Profile')
    Post = apps.get_model('mist', 'Post')
    Vote = apps.get_model('mist', 'Vote')
    Flag = apps.get_model('mist', 'Flag')
    Comment = apps.get_model('mist', 'Comment')
    Message = apps.get_model('mist', 'Message')

    # Everything is updated with the new profile indexing system
    # BUT every model will now point directly to the user, not profile
    for post in Post.objects.all():
        post.temp_author = Profile.objects.get(username=post.author).user.pk
        post.save()
    
    for vote in Vote.objects.all():
        vote.temp_voter = Profile.objects.get(username=vote.voter).user.pk
        vote.save()
    
    for flag in Flag.objects.all():
        flag.temp_flagger = Profile.objects.get(username=flag.flagger).user.pk
        flag.save()
    
    for comment in Comment.objects.all():
        comment.temp_author = Profile.objects.get(username=comment.author).user.pk
        comment.save()

    for message in Message.objects.all():
        message.temp_from_user = Profile.objects.get(username=message.from_user).user.pk
        message.temp_to_user = Profile.objects.get(username=message.to_user).user.pk
        message.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0025_alter_profile_id_alter_profile_username'),
    ]

    operations = [

        migrations.AddField(
            model_name='post',
            name='temp_author',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='temp_voter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='temp_flagger',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='temp_author',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='temp_from_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='temp_to_user',
            field=models.IntegerField(null=True),
        ),


        migrations.RunPython(
            code=match,
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.RemoveField(model_name='post', name='author'),
        migrations.RemoveField(model_name='vote', name='voter'),
        migrations.RemoveField(model_name='flag', name='flagger'),
        migrations.RemoveField(model_name='comment', name='author'),
        migrations.RemoveField(model_name='message', name='from_user'),
        migrations.RemoveField(model_name='message', name='to_user'),
        
        migrations.RenameField(
            model_name='post', old_name='temp_author', new_name='author'),
        migrations.RenameField(
            model_name='vote', old_name='temp_voter', new_name='voter'),
        migrations.RenameField(
            model_name='flag', old_name='temp_flagger', new_name='flagger'),
        migrations.RenameField(
            model_name='comment', old_name='temp_author', new_name='author'),
        migrations.RenameField(
            model_name='message', old_name='temp_from_user', new_name='from_user'),
        migrations.RenameField(
            model_name='message', old_name='temp_to_user', new_name='to_user'),

        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL)
        ),     
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL)
        ),
        migrations.AlterField(
            model_name='flag',
            name='flagger',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL)
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL)
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL)
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL)
        ),
    ]
