# Generated by Django 4.0.6 on 2022-08-04 06:10

from django.db import migrations, models
import django.db.models.deletion

def delete_all_tags(apps, schema_editor):
    Tag = apps.get_model('mist', 'Tag')
    Tag.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0026_tag_tagged_name_tag_tagged_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.RunPython(delete_all_tags, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='tag',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.comment'),
            preserve_default=False,
        ),
    ]
