# Generated by Django 4.0.6 on 2022-08-04 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0027_remove_tag_post_tag_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagged_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagging_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
