# Generated by Django 4.0.4 on 2022-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0027_alter_message_from_user_alter_message_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='posts',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flag',
            name='post',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.CharField(max_length=10),
        ),
    ]
