# Generated by Django 4.0.6 on 2022-08-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0028_alter_tag_tagged_user_alter_tag_tagging_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tagged_user', 'tagging_user'), name='tagged_user_tagging_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tagged_phone_number', 'tagging_user'), name='tagged_phone_number_tagging_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tagged_phone_number__isnull', False), ('tagged_user__isnull', True)), models.Q(('tagged_phone_number__isnull', True), ('tagged_user__isnull', False)), _connector='OR'), name='mist_tag_thing1_or_thing2'),
        ),
    ]
