# Generated by Django 4.0.4 on 2022-05-15 22:21

from django.db import migrations, models

def create_ids(apps, schema_editor):
    Post = apps.get_model('mist', 'Post')
    posts = Post.objects.all()
    i = 1
    for p in posts:
        p.temp_id = i
        i += 1
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0028_remove_word_posts_alter_comment_post_alter_flag_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_id',
            field=models.BigIntegerField(null=True)
        ),
        migrations.RunPython(
            code=create_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RenameField(
            model_name='post', old_name='temp_id', new_name='id'),     
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
