# Generated by Django 4.0.4 on 2022-05-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0029_post_new_primary_key'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE mist_comment ALTER post TYPE bigint USING post::bigint;'),
        migrations.RunSQL('ALTER TABLE mist_flag ALTER post TYPE bigint USING post::bigint;'),
        migrations.RunSQL('ALTER TABLE mist_vote ALTER post TYPE bigint USING post::bigint;'),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
        ),
    ]
