# Generated by Django 4.0.6 on 2022-08-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0029_tag_tagged_user_tagging_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='mist_tag_thing1_or_thing2',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tagged_phone_number__isnull', False), ('tagged_user__isnull', True)), models.Q(('tagged_phone_number__isnull', True), ('tagged_user__isnull', False)), _connector='OR'), name='mist_tag_tagged_phone_number_or_tagged_user'),
        ),
    ]
