# Generated by Django 4.0.4 on 2022-05-15 22:39

from django.db import migrations, models
import django.db.models.deletion

from mist.serializers import FlagSerializer

def assign_to_first_post(apps, schema_editor):
    Comment = apps.get_model('mist', 'Post')
    Flag = apps.get_model('mist', 'Flag')
    Vote = apps.get_model('mist', 'Vote')
    comments = Comment.objects.all()
    votes = Vote.objects.all()
    flags = Flag.objects.all()
    for c in comments:
        c.temp_post = 1
    for f in flags:
        f.temp_post = 1
    for v in votes:
        v.temp_post = 1

class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0029_post_new_primary_key'),
    ]

    operations = [

        migrations.AddField(
            model_name='comment',
            name='temp_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='temp_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='temp_post',
            field=models.IntegerField(null=True),
        ),

        migrations.RunPython(
            code=assign_to_first_post,
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.RemoveField(model_name='comment', name='post'),
        migrations.RemoveField(model_name='vote', name='post'),
        migrations.RemoveField(model_name='flag', name='post'),

        migrations.RenameField(
            model_name='comment', old_name='temp_post', new_name='post'),
        migrations.RenameField(
            model_name='vote', old_name='temp_post', new_name='post'),
        migrations.RenameField(
            model_name='flag', old_name='temp_post', new_name='post'),

        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post'),
        ),
    ]
