# Generated by Django 4.0.4 on 2022-05-15 22:49

from django.db import migrations, models
import uuid

def create_uuids(apps, schema_editor):
    Post = apps.get_model('mist', 'Post')
    posts = Post.objects.all()
    for p in posts:
        p.uuid = uuid.uuid4()
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0030_alter_comment_post_alter_flag_post_alter_vote_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),

        migrations.RunPython(
            code=create_uuids,
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
