# Generated by Django 4.0.4 on 2022-05-15 23:08

from django.db import migrations, models

def create_ids(apps, schema_editor):
    Word = apps.get_model('mist', 'Word')
    words = Word.objects.all()
    i = 1
    for w in words:
        w.id = i
        i += 1
        w.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0031_post_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='id',
            field=models.BigIntegerField(null=True)
        ),
        migrations.RunPython(
            code=create_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=100, unique=True)
        ),     
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
