# Generated by Django 4.0.6 on 2022-08-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0032_remove_tag_tagged_user_tagging_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='emoji',
            field=models.CharField(default='❤️', max_length=5),
        ),
    ]
