# Generated by Django 4.0.4 on 2022-05-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0032_word_new_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='posts',
            field=models.ManyToManyField(to='mist.post'),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
