# Generated by Django 4.0.7 on 2022-08-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0033_alter_postvote_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='mist.comment'),
        ),
    ]
