# Generated by Django 4.0.4 on 2022-05-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0034_comment_new_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
