# Generated by Django 4.0.7 on 2022-08-30 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0034_alter_tag_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MistboxPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mist.mistbox')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mist.post')),
            ],
        ),
    ]
