# Generated by Django 4.0.7 on 2022-08-31 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0035_mistbox_mistboxpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mistboxpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistbox_post', to='mist.post'),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
