# Generated by Django 4.0.4 on 2022-05-18 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0035_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
