# Generated by Django 4.0.7 on 2022-09-01 05:53

from django.db import migrations, models
import users.generics


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0036_alter_mistbox_user_alter_mistboxpost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistbox',
            name='date',
            field=models.DateField(default=users.generics.get_current_date),
        ),
    ]
