# Generated by Django 4.0.7 on 2022-09-02 21:58

from django.db import migrations, models
import mist.models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0037_mistbox_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistbox',
            name='timestamp',
            field=models.FloatField(default=mist.models.get_current_time),
        ),
        migrations.AddField(
            model_name='post',
            name='time_created',
            field=models.FloatField(default=mist.models.get_current_time),
        ),
    ]
