# Generated by Django 4.0.4 on 2022-05-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0037_rename_registration_userregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='EmailAuthentication',
        ),
    ]
