# Generated by Django 4.0.7 on 2022-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0038_mistbox_timestamp_post_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mistboxes',
            field=models.ManyToManyField(related_name='posts', to='mist.mistbox'),
        ),
        migrations.DeleteModel(
            name='MistboxPost',
        ),
    ]
