# Generated by Django 4.0.7 on 2022-09-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0041_alter_post_mistboxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mistbox',
            name='date',
        ),
    ]
