# Generated by Django 4.0.7 on 2022-09-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0042_remove_mistbox_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistbox',
            old_name='timestamp',
            new_name='time_created',
        ),
    ]
