# Generated by Django 4.0.7 on 2022-09-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0043_rename_timestamp_mistbox_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistbox',
            old_name='time_created',
            new_name='creation_time',
        ),
    ]
