# Generated by Django 4.0.7 on 2022-09-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0044_rename_time_created_mistbox_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mistboxes',
        ),
    ]
