# Generated by Django 4.0.7 on 2022-09-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0045_remove_post_mistboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistbox',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='mist.post'),
        ),
    ]
