# Generated by Django 4.0.7 on 2022-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0046_mistbox_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistbox',
            name='posts',
            field=models.ManyToManyField(blank=True, to='mist.post'),
        ),
    ]
