# Generated by Django 4.0.7 on 2022-09-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0048_mistbox_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistbox',
            old_name='posts',
            new_name='deleted_posts',
        ),
    ]
