# Generated by Django 4.0.7 on 2022-09-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0049_rename_posts_mistbox_deleted_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistbox',
            old_name='deleted_posts',
            new_name='swiped_posts',
        ),
    ]
