# Generated by Django 4.0.7 on 2022-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0050_rename_deleted_posts_mistbox_swiped_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistbox',
            old_name='swiped_posts',
            new_name='posts',
        ),
        migrations.AddField(
            model_name='mistbox',
            name='swipecount',
            field=models.IntegerField(default=0),
        ),
    ]
