# Generated by Django 4.0.7 on 2022-09-04 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0051_rename_swiped_posts_mistbox_posts_mistbox_swipecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistbox',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mistbox', to=settings.AUTH_USER_MODEL),
        ),
    ]
