# Generated by Django 4.0.7 on 2022-09-04 21:43

import django.contrib.postgres.fields
from django.db import migrations, models
import users.generics


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0052_alter_mistbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistbox',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=users.generics.get_empty_keywords, size=5),
        ),
    ]
