# Generated by Django 4.0.7 on 2022-09-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0054_alter_mistbox_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_created',
            new_name='creation_time',
        ),
        migrations.AlterField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mist.post'),
        ),
    ]
