# Generated by Django 4.0.7 on 2022-09-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0055_rename_time_created_post_creation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistbox',
            old_name='swipecount',
            new_name='opens_used_today',
        ),
    ]
