# Generated by Django 4.0.7 on 2022-09-07 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0058_alter_accesscode_claimed_user_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mist.post'),
        ),
        migrations.AlterField(
            model_name='postflag',
            name='flagger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postflags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postflag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='mist.post'),
        ),
        migrations.AlterField(
            model_name='postflag',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
