# Generated by Django 4.0.7 on 2022-09-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0059_alter_comment_post_alter_postflag_flagger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentflag',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
