# Generated by Django 4.0.7 on 2022-09-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0060_alter_commentflag_rating_alter_commentvote_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
