# Generated by Django 4.0.7 on 2022-09-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0061_alter_postvote_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code_string',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
