# Generated by Django 4.0.7 on 2022-09-09 03:29

from django.db import migrations, models

def set_all_default_ratings_to_one(apps, schema_editor):
    PostVote = apps.get_model("mist", "PostVote")
    CommentVote = apps.get_model("mist", "CommentVote")
    PostFlag = apps.get_model("mist", "PostFlag")
    CommentFlag = apps.get_model("mist", "CommentFlag")

    for post_vote in PostVote.objects.all():
        post_vote.rating = 1
        post_vote.save()

    for comment_vote in CommentVote.objects.all():
        comment_vote.rating = 1
        comment_vote.save()

    for post_flag in PostFlag.objects.all():
        post_flag.rating = 1
        post_flag.save()

    for comment_flag in CommentFlag.objects.all():
        comment_flag.rating = 1
        comment_flag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0062_alter_accesscode_code_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentflag',
            name='rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='postflag',
            name='rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='rating',
            field=models.FloatField(default=1),
        ),
        migrations.RunPython(set_all_default_ratings_to_one, migrations.RunPython.noop),
    ]
