# Generated by Django 4.0.7 on 2022-09-13 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mist', '0064_alter_block_blocked_user_alter_block_blocking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentflag',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='mist.comment'),
        ),
        migrations.AlterField(
            model_name='commentflag',
            name='flagger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentflags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mist.comment'),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
