# Generated by Django 4.0.7 on 2022-09-17 22:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0066_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=Decimal('34.02239999999999753299562144093215465545654296875')),
        ),
    ]
