# Generated by Django 4.0.7 on 2022-09-17 22:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0067_alter_post_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=Decimal('118.28509999999999990905052982270717620849609375')),
        ),
    ]
