# Generated by Django 4.0.7 on 2022-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0070_message_is_hidden_collectible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='collectible_type',
            field=models.PositiveIntegerField(),
        ),
    ]
