# Generated by Django 4.0.7 on 2022-09-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0071_alter_collectible_collectible_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectibles', to='mist.post'),
        ),
    ]
