# Generated by Django 4.0.7 on 2022-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0076_alter_post_latitude_alter_post_location_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
